server:
  port: 8086

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/stayease_payment_db
    username: root
    password: 2000030757
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

services:
  booking:
    url: http://localhost:8085

Razorpay:
  key-id: rzp_test_Sf0goLCDZ1ev3P
  key-secret: Go22krJbTtjJcqLMh3ca9e2G

logging:
  level:
    root: INFO
    com.stayease.payment_service: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    io.github.resilience4j: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

resilience4j:
  retry:
    instances:
      razorpayRetry:
        max-attempts: 3
        wait-duration: 500ms
      bookingRetry:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - feign.FeignException
          - java.io.IOException

  circuit breaker:
    instances:
      razorpayCB:
        registerHealthIndicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
      bookingCB:
        registerHealthIndicator: true
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
  rate limiter:
    instances:
      paymentAPI:
        limit-for-period: 200
        limit-refresh-period: 1m
        timeout-duration: 5s
      razorpayAPI:
        limit-for-period: 50
        limit-refresh-period: 10s
        timeout-duration: 3s

payment:
  reconciliation:
    interval: 300000   # 5 min
  order:
    expiry: 900        # 15 min
  refund:
    enabled: true
    maxRefundDays: 30

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: FULL